name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "59 15 * * *" # 每天 UTC 时间 15:59 运行（即北京时间 23:59），避免过于频繁的请求
  workflow_dispatch: # 直接通过 GitHub Actions 工作流程页面手动运行工作流程（无需等待调度）
permissions:
  contents: write # 将生成的内容写入 README 文件

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://marlin-phone.github.io/feed.xml" # 使用您的博客 RSS 源
